version: '3.8'
services:
  spring-app:
    build:
      context: .
      dockerfile: spring.dockerfile
    container_name: spring-rest-api
    ports:
      - '8000:8000'
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/librarydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgres-db:
    build:
      context: .
      dockerfile: postgres.dockerfile
    container_name: ${PG_CONTAINER_NAME}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
    ports:
      - '5432:5432'
    volumes:
      - dbvol:/data/postgres-librarydb
volumes:
  dbvol:
    external: true